apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: owner-picker-demo
  title: Test OwnerPicker component
  description: scaffolder v1beta3 template for testing OwnerPicker component
spec:
  owner: backstage/techdocs-core
  type: service

  parameters:
    - title: Fill in some steps
      required:
        - owner
      properties:
        owner:
          title: Owner
          type: string
          description: Testing OwnerPicker component
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind: Group
  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./template
        values:
          name: ${{ parameters.name }}
          owner: ${{ parameters.owner }}
    - id: fetch-docs
      name: Fetch Docs
      action: fetch:plain
      input:
        targetPath: ./community
        url: https://github.com/backstage/community/tree/main/backstage-community-sessions
